---
- name: Check if swap file exists
  stat:
    patch: "{{ swap_file }}"
  register: swap_file_check

- name: Create swap file
  command: fallocate -l {{ swap_size }} {{ swap_file }}
  when: not swap_file_check_stat.exists

- name: Set permissopns on swap file
  file:
    path: "{{ swap_file }}"
    mode: 0600

- name: Make swap
  command: mkswap {{ swap_file }}
  when: not swap_file_check_stat.exists

- name: Add swap to fstab
  lineinfile:
  dest: /etc/fstab
  regexp: "{{ swap_file }}"
  line: "{{ swap_file }} none swap sw 0 0"

- name: Turn on swap
  command: swapon -a

- name: Set swapness
  sysctl:
    name: vm.swappiness
    value: "1"