---
- name: Install Docker SDK dependencies
  apt:
    name:
      - python3-pip
      - virtualenv
      - python-setuptools
    state: present
    update_cache: yes

- name: Install Docker SDK for Python
  pip:
    name: docker